### ISSUE TITLE
Add support for django 3.2

### ISSUE THREAD

**Issue by ronaldgrn** [liminspace/django-mjml#125]

**Comment by hvdklauw** [comment]
I don't see a reason why django 3.2 wouldn't work except that the [setup.py](https://github.com/liminspace/django-mjml/blob/master/setup.py#L20) limits django to <3.2

**Comment by ronaldgrn** [comment]
It does work fine, I just much prefer use the official package via a pip install instead of a fork that changes one line.

**Comment by hvdklauw** [comment]
Oh yeah, I agree. My point was that it seems a trivial thing to fix

**Comment by liminspace** [comment]
I just need extra time to migrate to github actions from greedy travis..

**Comment by alaskanpuffin** [comment]
Any update on this?

**Comment by hairypalm** [comment]
+1 please.  We need this . . ..  Looks like there is already a PR with the fix in from May.  Thanks for the great package!

**Comment by liminspace** [comment]
0.11.0 has been released ;)
