### ISSUE TITLE
Mock httpserver

### ISSUE THREAD

**Issue by aabanaag** [liminspace/django-mjml#134]
I added the httpserver config, but running my test fails because of the ` RuntimeError: MJML compile error (via MJML HTTP server):`

Is there a way to mock the MJML calls? I'm doing a mock on the actual email sending

```
with patch("requests.post") as mock_post:
     mock_post.return_value(ok=True, status=status.HTTP_201_CREATED)
```

**Comment by liminspace** [comment]
@aabanaag try to mock `MJMLRenderNode.render` or `mjml_render` or `_mjml_render_by_httpserver`

**Comment by aabanaag** [comment]
Thank you, I got it by mocking _mjml_render_by_httpserver
