### ISSUE TITLE
Dont start the server with django-mjml.

### ISSUE THREAD

**Issue by vcrodes** [liminspace/django-mjml#15]
Hi, 

today i begin to use the django-mjml. Following the instructions I can't start the server. I detected a problem in app.py on the function check_mjml_command(). The issues is around the test, the test_mjml is on version 3 of mjml, and with the new version 4 can pass the test and dont start the server. If I change the string test_mjml to '<mjml><mj-body><mj-section><mj-column></mj-column></mj-section></mj-body></mjml>' the test pass without problem.

With this little change I can start the server without problems.

**Comment by liminspace** [comment]
Thanks, I'll check it.

**Comment by liminspace** [comment]
@vcrodes, as temporary solution you can use mjml 3.3.5. It works file.
New version django-mjml will be released a bit later.

**Comment by liminspace** [comment]
This issue is done in next release 0.5.0
