### ISSUE TITLE
Update to support Django 4.0

### ISSUE THREAD

**Issue by stenius** [liminspace/django-mjml#152]
Hey @liminspace, I'd like to use this with Django 4.0.  Is there any particular reason you have it set to use versions of django < 3.3?

If I opened up a PR to update it, would you be interested in helping me get it merged in?

Thanks,
-Paul

**Comment by cavanierc** [comment]
Hey, 
I did a PR #153 , awaiting review,
Thank you

**Comment by liminspace** [comment]
@cavanierc, I'll review the changes and release new version this week. Thanks!

**Comment by mvaled** [comment]
Hi @liminspace 

I've been using @cavanierc branch since Jan, 6th.  Nothing to report.  I think this could be merged and released.

**Comment by liminspace** [comment]
Hi, I've released 0.12.0. Sorry for delaying.
