### ISSUE TITLE
Ignore stderr punycode deprecation warning

### ISSUE THREAD

**Issue by alfonsrv** [liminspace/django-mjml#188]
Cannot use this anymore due to the `(node:60710) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.` error. I tried working around this, but found out `mjml` itself depends on libraries directly linked to punycode (see https://github.com/mjmlio/mjml/issues/2843)

I have previously worked around this issue by downgrading node, but that's not really a fix; especially since basically a year later it's still the same.

Can we ignore stderr involving these lines to avoid crashing the wrapper?

```
(node:60953) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by liminspace** [comment]
Python-side code shouldn't handle issues from node-side. This issue can be fixed by using LTS version of node or using stable version of mjml.

**Comment by fernandolins** [comment]
@liminspace, your answer is incompleted. I was using a node LTS Version and a stable version of mjml, but I still had this issue.

In this case, I was using Node LTS 22.11.0 (Jod) version and it didn't work. 

To solve this problem, I had to downgrade to Node LTS 20.18.0 (iron) version.

Maybe there should be the right node version to use in the readme file.
