### ISSUE TITLE
Ignore npm notice New major version of npm available! 9.8.0 -> 10....

### ISSUE THREAD

**Issue by alexanderhupfer** [liminspace/django-mjml#191]
RuntimeError: MJML stderr is not empty: mjml-migrate is deprecated and will be removed in mjml 5

This should probably be a warning instead.

**Comment by liminspace** [comment]
This issue is not related to django-mjml. Try to check your mjml-code and be sure you use new tags. Also you can use older version of mjml if you prefer using old mjml-tags.
