### ISSUE TITLE
Message in stderr is breaking django-mjml

### ISSUE THREAD

**Issue by rosacris** [liminspace/django-mjml#74]
Mjml v4.2.1 was released with a change that moves all messages from stdout to stderr to prevent these being mixed with the resulting html.
This is breaking django-mjml command here https://github.com/liminspace/django-mjml/blob/9dd6bf1b124e1e0dadf6700edf46ead56d144aa2/mjml/tools.py#L39
For example, if you are still using v3 of mjml syntax, with version 4.2.1 you will get the following error in stderr:
```
MJML v3 syntax detected, migrating to MJML v4 syntax. Use mjml -m to get the migrated MJML.
```
This will make `_mjml_render_by_cmd` raise a `RuntimeError`

**Comment by liminspace** [comment]
@rosacris, have you tried to use MJML-option `--mjml.validationLevel=stric` or `--mjml.validationLevel=skip`?

**Comment by rosacris** [comment]
I have tried all levels, but the warning is still appearing in stderr.

**Comment by liminspace** [comment]
@rosacris 

What do you expect? Django-mjml should render warnings in result? I thing it is not a good idea.

We can't distinguish between errors and warning as we have only one pipe -- stderr.
I think it's MJML's part and if some error or warning is happend you will get error and can fix it. Or you can disable mjml-validation by using --mjml.*-parameters.

Moreover, using cmd-mode is not a good practice. It can be used only for test. But even for testing and developing I use docker and mjml-tcpserver.

So, give me more information about problem you have and how we can resolve it.

**Comment by rosacris** [comment]
I do not expect anything, it is no longer a problem for me because I have updated my MJML templates to V4.
I just wanted to inform you that after a minor version update of MJML the API has changed and now there are way many more things being reported through stderr that are not actual errors. Perhaps it is useful for someone.

**Comment by matteing** [comment]
I can report this.

**Comment by liminspace** [comment]
> I can report this.

Hi, what do you mean?

**Comment by ngarnier** [comment]
Hey guys, just wanted to let you know that we're going to revert this change, please see https://github.com/mjmlio/mjml/issues/1439#issuecomment-470137461.
