### ISSUE TITLE
Django Admin Widget

### ISSUE THREAD

**Issue by macmichael01** [liminspace/django-mjml#9]
It would be amazing to have an admin widget for email templates stored in the database for a live preview.

**I see 2 approaches:**
- Auto send a template render request (to a provided URL) on an interval or manually by pressing a render template button.
- Since the MJML was written in nodeJS, I would think it's possible to load this package as JavaScript in a browser for live preview functionality.

Thoughts?

**Comment by liminspace** [comment]
I try to keep this package as simple as possible. I think your feature is not typical.
MJML has API where you can render your templates edited in a browser https://mjml.io/api.
